# Site settings
title: Zankl Lab
subtitle: Skeletal Dysplasia Centre
email: andreas.zankl@sydney.edu.au  
description: Skeletal Dysplasia Research Group at the University of Sydney
baseurl: "/skeldys" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: Andreas Zankl   
street_address: The Children's Hospital at Westmead
city: Sydney
state: NSW
zip_code: 2145
country: Australia
phone: (02) 9845 3210

# Social settings
500px_url:
facebook_url:
github_url: https://github.com/azankl 
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: https://twitter.com/azankl
email_url: andreas.zankl@sydney.edu.au

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown
